### ISSUE TITLE
Consider tagging MELPA-compatible releases

### ISSUE THREAD

**Issue by ccharles** [chrisbarrett/emacs-refactor#3]
This package is available on MELPA, which is a great start. Unfortunately, you have not tagged any releases, so those of us using [MELPA Stable](melpa-stable.org/#/) are unable to easily use it.

When you are comfortable adding a stable release, please consider [adding MELPA-compatible tags](https://github.com/milkypostman/melpa#stable-packages) to your repository so `emr` shows up on MELPA Stable as well.

**Comment by AdrieanKhisbe** [comment]
@chrisbarrett should be good now that tag 0.3.6 was added :)
